import Car from "./car";
import Color from "./enums/Color";
import Door from "./enums/Door";
import Direction from "./enums/Direction";

const gol = new Car('volkswagen', Color.Silver, 4);

gol.openTheDoor(Door.LeftFront);
gol.closeTheDoor(Door.LeftFront);
gol.turnOn();
gol.speedUp();
gol.speedDown();
gol.turn(Direction.Left);
gol.speedUp();
gol.speedDown();
gol.turn(Direction.Rigth);
gol.speedUp();
gol.speedDown();
gol.turn(Direction.Rigth);
gol.speedUp();
gol.speedDown();
gol.stop();
gol.openTheDoor(Door.RigthBack);
gol.closeTheDoor(Door.RigthBack);
gol.speedUp();
gol.speedDown();
gol.turn(Direction.Rigth);
gol.turn(Direction.Rigth);
gol.speedUp();
gol.speedDown();
gol.turn(Direction.Left);
gol.turn(Direction.Left);
gol.speedUp();
gol.speedDown();
gol.turn(Direction.Rigth);
gol.speedUp();
gol.speedDown();
gol.stop();
gol.openTheDoor(Door.RigthBack);
gol.closeTheDoor(Door.RigthBack);
gol.speedUp();